rplidar/scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: range_filter
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false
        upper_threshold: 3.0 # Stops wavefront behavior (noticed around 3.7m)
        lower_threshold: 0.05
    filter2:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.40
        max_y: 0.48
        max_z: 2.0
        min_x: -0.55
        min_y: -0.48
        min_z: -1.0
        invert: false # activate to remove all points outside of the box


